tinyspeck/sleuth

- static/catapult-overrides/sleuth-overrides.css
Make netlog tables more visible in darkmode
> fix: improve netlog table readability in darkmode

- src/main/ipc.ts
- src/main/menu.ts
- src/renderer/components/app.tsx
Adds an Open Recent menu item. Feels like this is a useful feature because we open many sets of logs!
https://user-images.githubusercontent.com/16010076/146604095-7bf0225f-c5ea-4825-b306-9e4265c16a97.mp4
> feat: add recent document to menu

- src/renderer/components/welcome.tsx
- src/renderer/styles/welcome.less
> feat: add tooltip to long filenames

- src/renderer/components/preferences-datetime.tsx
- src/renderer/components/preferences.tsx
- src/renderer/styles/preferences.less
- aligns the prefs so they're not so misaligned
- show sample datetime in the datetime pref
> fix: improvements to prefs ui

- src/main/menu-template.ts
Adds a link to the Quip FAQ in the Help menu
> feat: add FAQ to help menu

- src/renderer/processor.ts
Add support for iOS timestamps with periods instead of colons (hh.mm.ss instead of hh:mm:ss)
> fix: support more ios timestamp formats

- src/utils/get-nice-greeting.ts
- Fixed "your rock, we know it" to "you rock, we know it"
- Added a couple more fun lines
- Added a Slack Anniversary easter egg that triggers on Feb 12
> fix: typo in touchbar copy

- .circleci/config.yml
> build: switch to aws code-sign runners

- package.json
This reverts commit ff5d7fc1fcfa5c3657bd8b380a4e796eea664681.
> chore: revert "v4.0.0-beta.1"

- package.json
- yarn.lock
might as well do this before the next release
> build: electron 31

- src/renderer/components/devtools-view.tsx
- test/renderer/rtl-new/devtools-view.test.tsx
These are very basic but show if an iframe can load and if we can display the table of threads.
> spec: add devtools-view tests

- src/renderer/components/app-core-header-filter.tsx
- src/renderer/state/sleuth.ts
Nice little quality of life feature. Also adds a little colour indicator for when you're actively using filters.
https://github.com/user-attachments/assets/8507a5d0-daed-4aed-99fe-c11c1e9a11fe
> feat(filter): add filter reset functionality

- static/index.html
> refactor: remove references to `electron/fiddle`

- src/renderer/components/app.tsx
Follow-up to #183
I deleted too much code, this restores some settings we actually need.
> fix(theme): apply correct colors for dark mode in antd

- package.json
- tsconfig.json
- yarn.lock
Pruning our dependency tree for unused dependencies.
> build(deps): prune dependency tree

- src/renderer/components/sidebar.tsx
Adds GPU label for saved gpu pages.
> feat: add gpu-info.html label

- src/renderer/processor.ts
Supports the new Android log timestamp format of YYYY-MM-DD THH:MM:SS.ssssss
e.g. `2025-04-11 T09:54:48.439006 -07:00 Message goes here`
> fix: support new android log format

- src/renderer/components/app.tsx
someone (cough) broke the home button so I fixed it
> fix: home button resets app again

- src/main/filesystem/open-file.ts
- src/renderer/components/app.tsx
> fix: correctly reset app on drag-and-drop

- src/renderer/components/preferences-editor.tsx
- src/renderer/components/preferences.tsx
- src/renderer/state/sleuth.ts
- src/utils/open-line-in-source.ts
1. Removes support for Atom and custom commands.
2. Adds support for Cursor.
> feat: clean up Open in Editor implementation

- src/preload/preload.ts
- src/renderer/components/app-core-header-filter.tsx
- src/renderer/styles/app-header.less
This guy was already a half-and-half.
> refactor: convert App Header to `antd`

- src/renderer/components/state-table.tsx
- src/renderer/styles/statetable.less
> refactor: migrate `state-table.tsx` to antd

- package.json
- yarn.lock
leftovers that we don't need anymore after https://github.com/tinyspeck/sleuth/pull/210
> chore: remove babel

- src/renderer/components/sidebar/sidebar-file-tree.tsx
> feat: warn about presence of crash dumps
