src/renderer/unzip.ts
Some zip files do not have separate directory trees, this can lead to us unzipping a file into a folder that does not yet exist.  Calling `mkdirp` on the parent directory of the target file ensures we never hit this case.
=> fix: handle zip files without directory trees

src/renderer/processor.ts
Fixes:
- Added Android regex to parse MMM-DD format
- Give Android debug lines (which have no timestamp) the closest timestamp because giving them a static date was breaking the new chart feature
- Added more comments so it won't take me 11 hours to fix it next time
- Added iOS DD/MM/YY format parsing
=> Android fix

src/renderer/components/welcome.tsx, src/renderer/suggestions.ts, test/renderer/rtl-new/welcome.test.tsx
Was using Sleuth today and I noticed that server downloaded profiles never seem to show up in the suggestions list, and that the "Delete files older than 2 days" functionality didn't seem to work either. I updated both the regex and the delete code to fix both.
=> fix: update server file regex and fix "delete all" feature

src/renderer/processor.ts, src/renderer/suggestions.ts
- Recognize files starting in `console` as console logs (vs requiring `console-export-`)
- Suggests files starting in `console` on the home screen
=> fix: improve console log parsing and suggestions

src/renderer/processor.ts
- branch name is wrong because I thought it was an Android issue at first lol
- I give debug lines in Android & browser with no timestamps a default 1970 date, then convert 1970 to the first actual date that appears in the logs - did it for Android, forgot to do it for console logs
=> fix: console logs no longer use incorrect timestamps

src/renderer/components/devtools-view.tsx, src/renderer/styles/devtools.less
- Performance profiles now display duration in seconds, start time, and end time
=> feat: add trace start, end, and duration

src/renderer/processor.ts
Two types of logs have weird timestamps:
- Some Android logs have no timestamp at all. In that case, we store those lines until we come across a line that _does_ have a timestamp. Then we give the stored lines that new timestamp and push it as one line.
- Some console logs have a time, but not date. In that case, we store those lines until we come across a line that does have a complete timestamp (i.e. date + time). Then we give the stored lines the new date, append the existing time, and push it as one line.
=> fix: console log lines now have proper timestamps

tools/fix-publish-paths.js
As in title, fixes the publish
=> build: ignore non-publish meta files in dry run folder

src/interfaces.ts, src/renderer/components/app-core.tsx, src/renderer/components/log-line-details/data.tsx, src/renderer/components/log-line-details/details.tsx, src/renderer/components/sidebar.tsx, src/renderer/processor.ts, test/utils/get-first-logfile.test.ts
This PR adds support for `electron_debug.log` in Sleuth. Chromium logs have a unique format that requires a whole other set of parsers.
A log line looks something like this:
```
[85509:0307/160606.126448:WARNING:transport_feedback_adapter.cc(263)] Failed to lookup send time for 1 packet. Send time history too small?
```
Here, the metadata prefixing the message is `[process_id:MMDD/hhmmss.SSSSSS:LOG_LEVEL:filename(line)]` as documented in https://support.google.com/chrome/a/answer/6271282.
Some notes:
* The timestamp is approximate: we don't have year information, but we assume that logs are fresh and sent within the last year or so.
* Log levels are not standard, so I mapped some obvious ones to the ones that Sleuth uses.
* We can actually link to Chrome's source to find the code where …
=> feat: add support for electron_debug.log

src/interfaces.ts, src/renderer/components/app-core-header-filter.tsx
Fixes #71 by rearranging the order of the Menu items in the App Header and in the interface's Log Level in the Renderer.
Importance: Rearranged the order to match order convention (Example: Order in Devtools).
=> fix: order log filters by log levels

src/renderer/components/app-core-header-filter.tsx
Fixes #72 by adding props to Date Range input component from Blueprint
Importance: Gives user option to select a single date and the time to filter by (see below).
**Before Change:**
https://github.com/tinyspeck/sleuth/assets/52749324/b16287a1-855a-4844-9edb-1ee8378b889d
**After Change:**
https://github.com/tinyspeck/sleuth/assets/52749324/f7730c2b-ee53-4a22-b026-be559f41c808
Notes:
- Time is in 24 hour format
=> feat: enabled single date filtering

src/ipc-events.ts, src/main/ipc.ts, src/renderer/components/mac-titlebar.tsx, src/renderer/ipc.ts
Fixes #74 by allowing Mac users to minimize/maximize their Sleuth window by double clicking the titlebar.
**Importance:** Matches convention of other Mac applications (VSCode, Electron Fiddle, etc) that users may use.
GIF of Change in Action:
https://github.com/tinyspeck/sleuth/assets/52749324/601564fb-61ba-4503-b1d1-0678fd77928d
=> feat: Minimize/Maximize on Double Click (MacOS)

src/interfaces.ts, src/main/touch-bar-manager.ts, src/renderer/analytics/notification-warning-analytics.tsx, src/renderer/components/app-core-header-filter.tsx, src/renderer/components/app-core.tsx, src/renderer/components/log-content.tsx, src/renderer/components/log-table.tsx, src/renderer/components/log-time-view.tsx, src/renderer/components/preferences.tsx, src/renderer/components/sidebar.tsx, src/renderer/components/spotlight.tsx, src/renderer/processor.ts, src/renderer/processor/performance.ts, src/renderer/state/bookmarks.ts, src/renderer/state/sleuth.ts, src/renderer/suggestions.ts, test/__mocks__/processed-log-file.ts, tsconfig.json
This is a prerequisite for #65.
Disabling a bad `tsconfig.json` setting so that we have an easier time migrating to ESLint. This changes up a lot of the LogFile types, which honestly need even more cleanup after this.
=> refactor: `suppressImplicitAnyIndexErrors: false`

.circleci/config.yml
Updates the Ubuntu Docker image to Node 16 and drops Fedora support.
=> build: update docker image to Node 16

src/main/windows.ts, test/__mocks__/electron.ts
Fixes #67 by disabling Electron remote module in WebPreferences and removing all instances of remote
=> fix: Disable remote module

src/renderer/state/sleuth.ts
I overcooked a bit in #93 and broke localStorage settings with my new `retrieve<T>` function.
=> fix(settings): respect localStorage settings

src/renderer/components/sidebar.tsx, src/renderer/state/sleuth.ts, yarn.lock
Two bugs here:
1. `logType in LogType` didn't work because string enums don't have a reverse map.
2. I forgot to assign `this.selectedLogFile`.
=> fix(sidebar): merge logs work again

src/renderer/components/log-content.tsx, src/renderer/components/log-table-constants.ts, src/renderer/components/log-table.tsx, src/renderer/components/number-results.tsx, src/renderer/styles/logtable.less, src/renderer/styles/numberOfResults.less, src/renderer/styles/styles.less, test/renderer/rtl-new/numberOfResults.test.tsx
Fixes https://github.com/tinyspeck/sleuth/issues/80 by displaying the number of search results on top of the table and added a couple of tests for displaying the correct number and format + grammar.
Importance: Allows the user to see how many results match their filtering or search
https://github.com/tinyspeck/sleuth/assets/52749324/24541616-939d-4bcf-8cc1-6d7b7047c1d1
=> feat: display number of results

package.json, src/ipc-events.ts, src/main/index.ts, src/main/ipc.ts, src/main/security.ts, src/main/windows.ts, src/renderer/components/app.tsx, yarn.lock
Sleuth is currently running on Electron v13.3.0, which is not a stable version ([see here](https://releases.electronjs.org/)). To stay up to date with security best practices, bug fixes, performance enhancements and future maintenance, upgrading Sleuth to the latest stable version is needed. 
This PR upgrades Sleuth to Electron v25.2.0 (latest at this time) and fixes #68 
-  When loading up Sleuth in `DevMode`, a white window will appear for a few seconds before Sleuth appears. This doesn't appear in production and doesn't impact performance.
- Removed `app.allowRendererProcessReuse` as it is no longer supported and was [removed](https://releases.electronjs.org/release/v14.0.0) in Electron v14.0.0
- Removed `cache` from `type name` as it was removed from `app.getPath` …
=> build: Upgrade to latest Electron stable

src/interfaces.ts, src/renderer/components/app-core.tsx, src/renderer/components/log-table.tsx, src/renderer/components/sidebar.tsx, src/renderer/processor.ts, src/renderer/styles/colors.less, src/utils/get-first-logfile.ts, test/utils/get-first-logfile.test.ts
Due to Slack Calls being replaced by Huddles, the need to collect for `Call` logs is no longer needed. Therefore, removing support for them will be beneficial to Sleuth in terms of performance + code cleanliness.
ref #111
=> chore: remove support for call logs

src/interfaces.ts, src/renderer/components/app-core.tsx, src/renderer/components/log-table.tsx, src/renderer/components/sidebar.tsx, src/renderer/processor.ts, src/renderer/styles/colors.less, src/utils/get-first-logfile.ts, test/renderer/processor.test.ts, test/utils/get-first-logfile.test.ts
Due to `Renderer` logs being deprecated and being incorporated under `WebApp` logs, Sleuth no longer needs to collect them. Therefore, removing support for them will be beneficial to Sleuth in terms of performance + code cleanliness.
- Files starting with ` 'unknown' ` will now go under the LogType `WEBAPP`. This is due to the `unknown-web-contents-console.log` file, which is web app console output that is of unknown type, still being produced by Slack-Desktop. In the future, this type will be refined.
ref #111
=> chore: remove support for renderer logs

src/interfaces.ts, src/renderer/components/app-core.tsx, src/renderer/components/log-table.tsx, src/renderer/components/sidebar.tsx, src/renderer/processor.ts, src/renderer/styles/colors.less, src/utils/get-first-logfile.ts, test/renderer/processor.test.ts, test/utils/get-first-logfile.test.ts
Due to `Preload` logs being deprecated and being incorporated under `WebApp` logs, Sleuth no longer needs to collect them. Therefore, removing support for them will be beneficial to Sleuth in terms of performance + code cleanliness.
=> chore: remove support for preload logs

.circleci/config.yml
ref #69 
This PR creates the macOS universal build by adding the `'universal'` build to the `build-macos` arch along with other Mac related jobs such as `code-sign-macos` and their respective workflows
Fixes #69
=> build: Create macOS universal build

.git-blame-ignore-revs
Ignores 4a290fd25882b2667f8da8c0659e19eeee7ae875 in git blame.
See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
=> chore: ignore Prettier commit in blame

src/renderer/components/sidebar.tsx, test/renderer/rtl-new/sidebar.test.tsx
Sleuth currently shows all categories in the sidebar, regardless of if they have any files in them. This can be seen as bad UI due to them being clickable but doing nothing since no files appear under them. 
This PR solves this problem by hiding any category that has no files under them, resulting in cleaner and less cluttered UI. Also added tests to make ensure it hides the correct categories.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
https://github.com/tinyspeck/sleuth/assets/52749324/ee102bb6-f93f-4268-83a0-6ca836b1d95d
</td>
<td>
</td>
</tr>
</table>
fixes #118
=> feat: hide categories with no files in them

src/renderer/components/sidebar.tsx, src/renderer/components/state-table.tsx
Due to files starting with the prefix '`slack-'` and html files no longer existing, removing support for them is the best option in terms of code cleanliness and efficiency.
- Added labels for common state files that weren't accounted for
=> chore: remove looking for 'slack-' files + html

.circleci/config.yml
See https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
The previous regex that we used had a faulty pre-release check that failed to match valid semver such as `v4.0.0-beta.1`.
=> build: use semver regex for release jobs

src/interfaces.ts, src/renderer/analytics/highlight-search-results.tsx, src/renderer/components/log-table.tsx
This PR refactors #124 by adding `types` to the `highlight` function as well as removing the `set` function within the `highlight` function. 
- Added `highlightMessage` to `LogEntry` interface which allows for the `messageCellRenderer` to behave more closely to it did prior to #124 and remove the need for `originalText` to exist.
=> refactor: cleaning improved search PR

.circleci/config.yml
Code signing now should work. Tested in commit [0e536b3](https://github.com/tinyspeck/sleuth/pull/132/commits/0e536b3bd512e051756a4ed722a785c6823d9049).
=> ci: load OIDC secrets into codesign job

src/renderer/processor.ts
- Increase filename length from 14 to 20 (after the `Default_`) to support filenames like `Default_logs-redacted (10).txt`
Reported here: https://slack-pde.slack.com/archives/C8EH27UDT/p1701113267842639
=> fix: support longer ios filenames

src/renderer/components/preferences.tsx
As a complement to #135, the Dark Mode switcher should be moved out of the main menu bar.
=> feat: add dark mode to preferences menu

package.json, yarn.lock
`@ant-design/icons` should be a prod dependency and not a dev one.
For some reason, this broke the v3.5.2 build. The renderer process fails to launch and an import error is thrown. However, the v3.5.1 build where the dependency was added succeeded?
=> fix: move packages to correct dev/dependency spot

tools/parcel-build.js
Parcel attempts to use `hmr` flag even when `process.env.NODE_ENV=production` is set.
I took a look in `node_modules` and the implementation for the option looks like:
```js
const hmr = target === 'node' ? false : typeof options.hmr === 'boolean' ? options.hmr : watch;
```
Contrary to the code comment, it seems like the HMR server is started independently of the status of the `watch` flag:
```js
if (_this3.options.watch) {
_this3.watcher = new Watcher(); // Wait for ready event for reliable testing on watcher
if (process.env.NODE_ENV === 'test' && !_this3.watcher.ready) {
yield new Promise(resolve => _this3.watcher.once('ready', resolve));
}
_this3.watchedGlobs.forEach(glob => {
_this3.watcher.add(glob);
});
_this3.watcher.on('add', _this3.onAdd.bind(_this3));
_this3.watcher.on('change', …
```
=> build: disable `hmr` in parcel

.circleci/config.yml
Running into errors with the Publish flow, and it seems like $BASH_ENV is getting written with an error message at the environment loading step.
=> build: `--fail` cURL request for secret exchange

.vscode/settings.json
Not sure why we do this, it's a bit annoying when I want to quickly access the output of `yarn package`.
=> chore: stop hiding `/out/` in vscode

.circleci/config.yml
The `publish` job now works but is suspiciously missing the universal asset
=> build: add universal code-sign macos job to dependency for publish

src/renderer/components/log-table.tsx
=> feat(log-table): tag process types when viewing All Desktop Logs

src/renderer/components/log-table-constants.ts, src/renderer/components/log-table.tsx
Alternative to #146.
On a larger scope, I'm not sure about the advantage of manually controlling shouldComponentUpdate when MobX should be controlling this as an `@observer` class.
This defers component updates back to MobX and deletes some redundant local state properties.
=> perf(log-table): just let updates happen

package.json, yarn.lock
Upgrade Sleuth to the latest Electron release. No [deprecations or breaking changes](https://www.electronjs.org/docs/latest/breaking-changes) since v25 seem to affect Sleuth.
=> chore: upgrade to electron@30

package.json, src/main/scheme.ts, src/renderer/processor/interfaces.ts, src/renderer/processor/trace.ts, yarn.lock
| Before | After |
| --- | --- |
| <img width="2032" alt="Screenshot 2024-05-17 at 6 44 54 PM" src="https://github.com/tinyspeck/sleuth/assets/1656324/68d3caf5-ff62-4e45-83d6-6f87352230c4"> | <img width="2032" alt="Screenshot 2024-05-17 at 6 45 44 PM" src="https://github.com/tinyspeck/sleuth/assets/1656324/254c8479-f8c2-4cd8-bec4-c8de58efda0b"> |
- Fit timeline to trace start time rather than app start time 0af6880476222c826c7845d1c8a7d10ad0263f84
- Update chrome devtools frontend 79b158beeab498c0a282956c22e5e5e22c72385f
- Migrate `oop://` to new handler API 3ef3ad08b66eb1e42919e1fe19570a3ce1fcd59c
=> chore: update devtools

.circleci/config.yml
Adds the correct environment variable context to pull the code-sign runner's entrypoint code.
See [successful run](https://app.circleci.com/pipelines/github/tinyspeck/sleuth/594/workflows/c4cfdce1-33ec-4433-a473-f4bdd94ff55f/jobs/3630) on commit 114584d.
=> ci: add `sleuth-code-signing` context

src/renderer/components/devtools-view.tsx, src/renderer/processor/interfaces.ts, src/renderer/processor/trace.ts, src/renderer/state/sleuth.ts
_this is a non-fork branched PR based on #153_
- Changes "Renderer Threads" to "Threads"
- Shows main process thread first
| Before | After |
| --- | --- |
| <img width="1282" alt="Screenshot 2024-05-16 at 6 58 10 PM" src="https://github.com/tinyspeck/sleuth/assets/1656324/d1334bf8-9ad2-4e4b-9ca6-4a16bb69572c"> | <img width="1282" alt="Screenshot 2024-05-16 at 6 57 37 PM" src="https://github.com/tinyspeck/sleuth/assets/1656324/903ada18-bf46-4006-a57e-262a9a45f306"> |
| No main process trace explorer 😭 | <img width="1282" alt="Screenshot 2024-05-16 at 7 02 25 PM" src="https://github.com/tinyspeck/sleuth/assets/1656324/28a1e8f1-1fa4-4ca5-883e-0aa2a2f677b4"> |
=> feat: show browser process in performance profile view

src/renderer/analytics/environment-analytics.tsx, src/renderer/components/sidebar.tsx
Performance issues may arise on macOS if a user installs `Slack.dmg` but keeps running the app from the mounted volume rather than installing their app into `/Applications`.
This PR adds a sidebar warning whenever this is the case.
=> feat: warn when user is running Slack from mounted DMG

.circleci/config.yml
Prevents us from wasting CI cycles if the quick `lint-and-test` job is gonna fail anyways.
=> ci: require `lint-and-test` before queuing builds

src/renderer/processor.ts
Mobile team is shipping a new standard timestamp format (https://github.com/tinyspeck/slack-objc/pull/88634), so added new regex and mobile parsing logic to support both the new ts and old ts formats
New format: 2024-07-10 T12:46:43.000043 -07:00
=> fix: support new mobile timestamp format

package.json, src/interfaces.ts, src/ipc-events.ts, src/main/ipc.ts, src/main/menu.ts, src/renderer/components/log-line-details/details.tsx, src/renderer/components/log-table.tsx, src/renderer/ipc.ts, src/renderer/state/copy.ts, src/utils/open-line-in-source.ts, yarn.lock
This PR adds context menus to log tables in Sleuth.
Menu items added:
* Copy Line: copies the line to your clipboard
* Show Line in Source: shows the log line in the source code of your default editor.
* Show in "All Desktop Logs" (desktop logs only): finds the corresponding log line in "All Desktop Logs" and jumps to the context.
https://github.com/user-attachments/assets/0a76e6b1-2905-4edf-b09e-0e529de7b27a
=> feat(log-table): useful context menus

.circleci/config.yml
This reverts commit ea008d849dd7fad677b7b6a20663466adb9fa421. Fixes the problem of tag publishes not working.
=> ci: revert "ci: require `lint-and-test` before queuing builds (#167)"

src/interfaces.ts, src/renderer/components/spotlight.tsx, src/renderer/components/welcome.tsx, src/renderer/state/sleuth.ts, src/renderer/styles/welcome.less, src/renderer/suggestions.ts
If we somehow consume a ZIP file that fails `yauzl` validation, this provides a cleaner UI that removes it from the suggestion list and renders the other files properly.
=> fix: escape hatch for invalid zip suggestions

src/renderer/styles/details.less
This PR addresses a small visual bug that occurs when switching. The example below is from resizing the Details pane, but this also happens when we switch between log lines that have different amount of JSON details.
https://github.com/user-attachments/assets/4425d35f-857d-4fff-bab7-88a2f99b1592
The solution for Chromium 94+ is elegant. With `scrollbar-gutter: stable`:
> When using classic scrollbars, the gutter will be present if overflow is auto, scroll, or hidden even if the box is not overflowing. When using overlay scrollbars, the gutter will not be present.
=> style: prevent layout shift when switching between log lines

src/renderer/analytics/trace-analytics.ts
There's a noticeable performance delay when clicking elements in the sidebar whenever a performance trace ZIP is loaded.
I ran a performance profile and it seems this delay comes from reading the JSON file to get trace warnings.
This PR uses `_.memoize` so that we only do this work once. For each log ZIP, we should actually only have one total value.
=> perf: memoize trace warnings

src/renderer/components/app-core.tsx, src/renderer/unzip.ts, test/renderer/unzip.test.ts
ZIP archives can contain multiple files with the same name. There's a longstanding Slack Desktop bug that generates files like these on Windows.
In order to process duplicate files properly, this PR increments non-unique file names with incrementing numbers so that we store them with unique file names on disk.
=> fix(unzip): ensure unique file names

package.json, src/ambient.d.ts, src/renderer/components/json-view.tsx, yarn.lock
Second follow-up PR to #183.
In this case, I blindly set the `invertTheme` parameter in `react-json-tree` to follow `isDarkMode`. Who would have guessed that "inverted" theme actually meant light mode? 🤦‍♂️
I also updated `react-json-tree` to 0.18.0 (latest CommonJS version) so that it actually has type definitions and we can avoid this problem in the future.
=> fix(theme): correct light/dark setting for JSON viz

src/renderer/styles/details.less
Tiny PR that fixes excessively long log lines not rendering properly.
=> fix: wrap excessively long log line descriptions

tsconfig.json
This fixes the problem where auto-imports would default to `src/main/my-file.ts` instead of using relative imports.
=> chore: remove `baseUrl` from tsconfig

src/renderer/components/preferences/preferences.tsx
Fixes a JS error preventing Sleuth from opening when `defaultEditor` is null.
=> fix: defaultEditor may be null

src/renderer/styles/details.less, src/renderer/styles/logtable.less, src/renderer/styles/scrollbar.less, src/renderer/styles/styles.less
Adds scrollbars back, changes padding, fixes some overlay issues with the details card.
=> style: minor layout tweaks

src/main/filesystem/read-file.ts
changes:
* completely removed androidDebug logic, which held onto the debug lines at the top of android logs in hopes of applying a new timestamp to them later on. we don't do this with ios; no reason to do it with android anymore
* changed how we handle console logs with no timestamps - apply a "No Date" string that is later updated, rather than applying an epoch timestamp which can cause crashes by breaking the histogram
=> fix: ignore Android metadata

src/renderer/components/log-line-details/details.tsx, src/renderer/styles/details.less
Reverts the details UX closer to what it used to be pre-antd :)
=> fix: more usable log line detail

.prettierignore, static/catapult-overrides/details_view.js
As-is, `yarn package` causes a diff due to some Prettier auto-format shenanigans. I've fixed a typo in `.prettierignore` to amend this.
=> chore: correct prettier setup for overrides
